#!/bin/bash

echo $CONFIG_FILE
echo $PWD
cat <<EOT >> $CONFIG_FILE
SWAGGER_BACKEND_URL = $SWAGGER_BACKEND_URL
SWAGGER_TITLE = $SWAGGER_TITLE
DB_HOST = $DB_HOST
DB_PORT = $DB_PORT
DB_USER = $DB_USER
DB_PASSWORD = $DB_PASSWORD
DB_NAME = $DB_NAME
JWT_SECRET = $JWT_SECRET
JWT_EXPIRES_IN = $JWT_EXPIRES_IN
REDIS_HOST = $REDIS_HOST
REDIS_PORT = $REDIS_PORT
REDIS_DB =
REDIS_PASSWORD =
REDIS_PREFIX = $REDIS_PREFIX
CORS_ORIGINS = $CORS_ORIGINS
GOOGLE_AUTH_CLIENT_ID = $GOOGLE_AUTH_CLIENT_ID
GOOGLE_AUTH_SECRET_ID = $GOOGLE_AUTH_SECRET_ID
EOT
